package com.settlet.mangia

class IngredientProvider {
    companion object{
        val ingredientList = listOf<Ingredient>(
            Ingredient(
                "Achiote",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Agracejo",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Ajenuz",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Ajowán",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Albahaca",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Achiote",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Alcaravea",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Angélica",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Anís",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Anís Estrellado",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Apio",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Azafrán",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Canela",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Cardamomo",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Carom",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Casia",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Cebolla deshidratada",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Cardamomo",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Cebollino",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Chile",
                "Polvo",
                0F,
                0
            ),
            Ingredient(
                "Chiles mexicanos",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Cilantro",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Clavo",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Comino",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Cúrcuma",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Dashi no moto",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Enebro",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Eneldo",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Epazote",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Estragón",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Fenogreco",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Galangal o galanga",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Granos del Paraíso",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Guindilla ojo de pájaro",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Haba tonka",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Hierba limón",
                "Gramos",
                0F,
                0
            ),
            Ingredient(
                "Hierbabuena o Sándalo",
                "Unidad",
                0F,
                0
            ),
            Ingredient(
                "Cardamomo",
                "Gramos",
                0F,
                0
            )
        )
    }
}